apiVersion: apps/v1
kind: Deployment
metadata:
  name: geostyle-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geostyle-app
  template:
    metadata:
      labels:
        app: geostyle-app
    spec:
      containers:
      - name: geostyle-app
        image: geostyle-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: face-profiles-config