apiVersion: v1
kind: Service
metadata:
  name: geostyle-service
  labels:
    app: geostyle
spec:
  type: LoadBalancer
  selector:
    app: geostyle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501