name: GeoStyle CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium (Checkout)
        uses: actions/checkout@v3

      - name: Konfiguracja środowiska Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Autoryzacja w rejestrze Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Konfiguracja Buildx (Optymalizacja cache)
        uses: docker/setup-buildx-action@v2

      - name: Kompilacja i eksport obrazu (Build and Push)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/geostyle-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/geostyle-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/geostyle-app:buildcache,mode=max

  kubernetes-validation:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium (Checkout)
        uses: actions/checkout@v3

      - name: Instalacja Kubeconform (Aktywny walidator)
        run: |
          wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Analiza manifestów klastra
        run: kubeconform -summary k8s/